"""empty message

Revision ID: 09e155e8fc10
Revises: 547cc713df16
Create Date: 2024-07-24 17:25:39.335962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e155e8fc10'
down_revision = '547cc713df16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint('fk_content_rss_link_rss', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_content_rss_link_rss'), 'rss', ['rss_link'], ['id'])

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(), nullable=False))
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_content_rss_link_rss'), type_='foreignkey')
        batch_op.create_foreign_key('fk_content_rss_link_rss', 'rss', ['rss_link'], ['link'])

    # ### end Alembic commands ###
