"""empty message

Revision ID: 1ca5ec9c6751
Revises: e71d1288c6e1
Create Date: 2024-07-18 16:15:49.736658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca5ec9c6751'
down_revision = 'e71d1288c6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
