"""empty message

Revision ID: 1dc23d6d6eac
Revises: ec2c6c5a89bd
Create Date: 2024-07-21 18:25:45.443165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc23d6d6eac'
down_revision = 'ec2c6c5a89bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=120), nullable=False))
        batch_op.alter_column('rss_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=120), nullable=False))
        batch_op.alter_column('rss_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
