"""empty message

Revision ID: 22f38e935095
Revises: 0edabc90429f
Create Date: 2024-07-20 18:58:46.743583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f38e935095'
down_revision = '0edabc90429f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_content_content'), ['content'])
        batch_op.create_unique_constraint(batch_op.f('uq_content_title'), ['title'])
        batch_op.drop_column('summarized_content')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_rss_description'), ['description'])
        batch_op.create_unique_constraint(batch_op.f('uq_rss_link'), ['link'])
        batch_op.create_unique_constraint(batch_op.f('uq_rss_title'), ['title'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_rss_title'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_rss_link'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_rss_description'), type_='unique')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summarized_content', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_content_title'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_content_content'), type_='unique')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
