"""empty message

Revision ID: 2c16150c56b8
Revises: 7abe5ab7efed
Create Date: 2024-07-21 18:38:09.650821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c16150c56b8'
down_revision = '7abe5ab7efed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rss_link', type_='unique')
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_rss_link', ['link'])

    # ### end Alembic commands ###
