"""empty message

Revision ID: 387a7b92bc5f
Revises: d17fca042d34
Create Date: 2024-07-21 18:07:35.876913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387a7b92bc5f'
down_revision = 'd17fca042d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_content_id_rss'), 'rss', ['id'], ['id'])
        batch_op.drop_column('content')
        batch_op.drop_column('title')
        batch_op.drop_column('rss_id')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_content_id_rss'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rss', ['rss_id'], ['id'])
        batch_op.drop_column('summary')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    # ### end Alembic commands ###
