"""empty message

Revision ID: 3f22c8c06bed
Revises: f5c1ce3e7ea9
Create Date: 2024-07-24 18:11:03.391954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f22c8c06bed'
down_revision = 'f5c1ce3e7ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
