"""empty message

Revision ID: 4009d3a7c05e
Revises: 1dc23d6d6eac
Create Date: 2024-07-21 18:26:41.706336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4009d3a7c05e'
down_revision = '1dc23d6d6eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_content')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=120), nullable=False))
        batch_op.alter_column('rss_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('title')
        batch_op.drop_column('content')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), nullable=False))
        batch_op.alter_column('rss_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('summary')

    op.create_table('_alembic_tmp_content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('summary', sa.VARCHAR(length=120), nullable=False),
    sa.Column('rss_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['rss_id'], ['rss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
