"""empty message

Revision ID: 44dcfe3c0098
Revises: 2c16150c56b8
Create Date: 2024-07-21 18:39:57.939602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44dcfe3c0098'
down_revision = '2c16150c56b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('uq_rss_description', type_='unique')
        batch_op.drop_constraint('uq_rss_title', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_rss_id'), ['id'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_rss_id'), type_='unique')
        batch_op.create_unique_constraint('uq_rss_title', ['title'])
        batch_op.create_unique_constraint('uq_rss_description', ['description'])
        batch_op.drop_column('content')

    # ### end Alembic commands ###
