"""empty message

Revision ID: 547cc713df16
Revises: d95d79d1be33
Create Date: 2024-07-24 17:23:22.173372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547cc713df16'
down_revision = 'd95d79d1be33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_link', sa.String(), nullable=False))
        batch_op.drop_constraint('fk_content_rss_id_rss', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_content_rss_link_rss'), 'rss', ['rss_link'], ['link'])
        batch_op.drop_column('rss_id')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_content_rss_link_rss'), type_='foreignkey')
        batch_op.create_foreign_key('fk_content_rss_id_rss', 'rss', ['rss_id'], ['id'])
        batch_op.drop_column('rss_link')

    # ### end Alembic commands ###
