"""empty message

Revision ID: 7abe5ab7efed
Revises: c382004fd0d1
Create Date: 2024-07-21 18:34:26.532136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abe5ab7efed'
down_revision = 'c382004fd0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
