"""empty message

Revision ID: 940afd66619f
Revises: 1ca5ec9c6751
Create Date: 2024-07-18 16:16:07.689307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940afd66619f'
down_revision = '1ca5ec9c6751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
