"""empty message

Revision ID: 9dc2fae29f4d
Revises: 44dcfe3c0098
Create Date: 2024-07-21 18:40:49.448997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc2fae29f4d'
down_revision = '44dcfe3c0098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rss')
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('uq_rss_description', type_='unique')
        batch_op.drop_constraint('uq_rss_title', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_rss_id'), ['id'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_rss_id'), type_='unique')
        batch_op.create_unique_constraint('uq_rss_title', ['title'])
        batch_op.create_unique_constraint('uq_rss_description', ['description'])
        batch_op.drop_column('content')

    op.create_table('_alembic_tmp_rss',
    sa.Column('id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_rss'),
    sa.UniqueConstraint('id', name='uq_rss_id')
    )
    # ### end Alembic commands ###
