"""empty message

Revision ID: c2c592397444
Revises: bc71f50f779e
Create Date: 2024-07-20 18:57:15.514842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c592397444'
down_revision = 'bc71f50f779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['content'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rss_id')
        batch_op.drop_column('summarized_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summarized_content', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('rss_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'rss', ['rss_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
