"""empty message

Revision ID: d17fca042d34
Revises: 22f38e935095
Create Date: 2024-07-20 19:31:44.370962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17fca042d34'
down_revision = '22f38e935095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint('uq_content_content', type_='unique')
        batch_op.drop_constraint('uq_content_title', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_content_title', ['title'])
        batch_op.create_unique_constraint('uq_content_content', ['content'])

    # ### end Alembic commands ###
