"""empty message

Revision ID: d21815b6bd4b
Revises: 940afd66619f
Create Date: 2024-07-19 22:11:08.717150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21815b6bd4b'
down_revision = '940afd66619f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('rss_id', sa.Integer(), nullable=False),
    sa.Column('summarized_content', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rss_id'], ['rss.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summarized_content'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
