"""empty message

Revision ID: e41cfa9e15dc
Revises: 9dc2fae29f4d
Create Date: 2024-07-24 17:02:27.578352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41cfa9e15dc'
down_revision = '9dc2fae29f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('uq_rss_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_rss_id', ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('link')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
