"""empty message

Revision ID: ec2c6c5a89bd
Revises: c8b1c5e6b42e
Create Date: 2024-07-21 18:18:06.112566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2c6c5a89bd'
down_revision = 'c8b1c5e6b42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rss_id')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('rss_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'rss', ['rss_id'], ['id'])
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
